BEGIN;

CREATE TABLE hb_shipping_address (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  address_id uuid NOT NULL PRIMARY KEY,
  address_line1 TEXT NOT NULL,
  address_line2 TEXT,
  city TEXT NOT NULL,
  state TEXT NOT NULL,
  zip INTEGER NOT NULL,
  user_id uuid REFERENCES hb_users(user_id) NOT NULL
);

CREATE TABLE hb_billing_address (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  address_id uuid NOT NULL PRIMARY KEY,
  address_line1 TEXT NOT NULL,
  address_line2 TEXT,
  city TEXT NOT NULL,
  state TEXT NOT NULL,
  zip INTEGER NOT NULL,
  user_id uuid REFERENCES hb_users(user_id) NOT NULL
);

COMMIT;